#!/bin/sh

##### Durfinder
# All 10.3.9 users of PunyVid <0.7 know durfinder well.
# This takes the crappy, useless H:M:S time that ffmpeg gives
# and converts it to plain ol' seconds.

H=`cat /tmp/punyvid_dur | grep Duration | awk -F \  '{print $2}' | sed s/,//g | awk -F : '{print $1}'`
M=`cat /tmp/punyvid_dur | grep Duration | awk -F \  '{print $2}' | sed s/,//g | awk -F : '{print $2}'`
S=`cat /tmp/punyvid_dur | grep Duration | awk -F \  '{print $2}' | sed s/,//g | awk -F : '{print $3}'`

## Did you know there are 3,600 seconds in an hour?
## I had to look that up.
H2=`echo "$H * 3600" | bc`
M2=`echo "$M * 60" | bc`
S2=`echo "$S"`

dur=`echo "$H2 + $M2 + $S2" | bc`
echo $dur > /tmp/punyvid_duration
