#!/bin/sh

##### RatioFinder
# I wrote this comment even before I typed
# a single line of code.
# I know it will work fine, because I have
# such great comments to work with.

## Take in the arguments.
optim=$1
tiny=$2
mpeg=$3

## Get the video's resolution, and turn it
## into an equation to get the aspect ratio.
origratio=`cat /tmp/punyvid_dur | grep fps | rev | awk -F ,p '{print $1}' | rev | awk -F , '{print $1}' | sed 's/ //g' | sed 's/x/ \/ /g' | bc -l | cut -c 1-3`
origres=`cat /tmp/punyvid_dur | grep fps | rev | awk -F ,p '{print $1}' | rev | awk -F , '{print $1}' | sed 's/ //g'`
origpx=`cat /tmp/punyvid_dur | grep fps | rev | awk -F ,p '{print $1}' | rev | awk -F , '{print $1}' | sed 's/ //g' | sed 's/x/ * /g' | bc`

#### Choose Your Destiny. ####
if [ "$origratio" == "1.2" ]
then
ratio=4by3
fi

if [ "$origratio" == "1.3" ]
then
ratio=4by3
fi

if [ "$origratio" == "1.4" ]
then
ratio=4by3
fi

## 1.5 is 720x480. This works nicely for most files,
## but MPEG-2 and DV files at this res might be 16:9.
## I check for the MPEG-2 ratio later, but can't do the same for DV.
if [ "$origratio" == "1.5" ]
then
ratio=4by3
fi

if [ "$origratio" == "1.6" ]
then
ratio=16by9
fi

if [ "$origratio" == "1.7" ]
then
ratio=16by9
fi

if [ "$origratio" == "1.8" ]
then
ratio=16by9
fi

if [ "$origratio" == "1.9" ]
then
ratio=16by9
fi

### ...and ultra-wide screen detection goes BACKWARDS! WOO!
if [ "$origratio" == "2.5" ]
then
ratio=wide
fi

if [ "$origratio" == "2.4" ]
then
ratio=wide
fi

if [ "$origratio" == "2.3" ]
then
ratio=wide
fi

if [ "$origratio" == "2.2" ]
then
ratio=wide
fi

if [ "$origratio" == "2.1" ]
then
ratio=wide
fi

if [ "$origratio" == "2" ]
then
ratio=wide
fi

## Use mpgtx's calculation of aspect ratio to
## correctly deal with anamorphic video.
if [ "$mpeg" == "1.77777777777777777777" ]
then
ratio=16by9
fi

if [ "$mpeg" == "1.33333333333333333333" ]
then
ratio=4by3
fi

## Compensate for HDV anamorphic weirdness.
if [ "$origres" == "1440x1080" ]
then
ratio=16by9
fi

if [ "$origres" == "1280x1080" ]
then
ratio=16by9
fi

if [ "$origres" == "960x720" ]
then
ratio=16by9
fi

## iPod screen settings.
if [ "$optim" == "ipod" ]
then
if [ "$tiny" == "tiny" ]
	then
		if [ "$ratio" == "4by3" ]
			then
			echo 240x176
			exit 0
			fi
		if [ "$ratio" == "16by9" ]
			then
			echo 240x128
			exit 0
			fi
		if [ "$ratio" == "wide" ]
			then
			echo 240x96
			exit 0
			fi
	else
		if [ "$ratio" == "4by3" ]
			then
			echo 320x240
			exit 0
			fi
		if [ "$ratio" == "16by9" ]
			then
			echo 320x176
			exit 0
			fi
		if [ "$ratio" == "wide" ]
			then
			echo 320x144
			exit 0
			fi
		fi
echo 320x240
exit 0
fi

## TV screen settings.
if [ "$optim" == "tv" ]
then
	if [ "$tiny" == "h264" ]
	then
		if [ "$origwidth" -le 640 ]
			then
			if [ "$origpx" -le 307200 ]
			then
			echo $origres
			exit 0
			fi
		fi
		if [ "$ratio" == "4by3" ]
				then
				echo 640x480
				exit 0
				fi
		if [ "$ratio" == "16by9" ]
				then
				echo 640x352
				exit 0
				fi
		if [ "$ratio" == "wide" ]
				then
				echo 640x272
				exit 0
				fi
			fi
		if [ "$tiny" == "tiny" ]
		then
			if [ "$ratio" == "4by3" ]
				then
				echo 400x304
				exit 0
				fi
			if [ "$ratio" == "16by9" ]
				then
				echo 480x272
				exit 0
				fi
			if [ "$ratio" == "wide" ]
				then
				echo 480x192
				exit 0
				fi
	else
##Use the video's original resolution if it's iPod-kosher.
		if [ $origpx -le 307200 ]
			then
			echo $origres
			exit 0
			fi
		if [ "$ratio" == "4by3" ]
			then
			echo 640x480
			exit 0
			fi
		if [ "$ratio" == "16by9" ]
			then
			echo 720x400
			exit 0
			fi
		if [ "$ratio" == "wide" ]
			then
			echo 720x304
			exit 0
			fi
		fi
echo 640x480
exit 0
fi

## iPod AV screen settings for Product From The Future. Based on assumption of 640x360.
if [ "$optim" == "ipodav" ]
then
	if [ "$tiny" == "tiny" ]
	then
		if [ "$ratio" == "4by3" ]
			then
			echo 400x304
			exit 0
			fi
		if [ "$ratio" == "16by9" ]
			then
			echo 480x272
			exit 0
			fi
		if [ "$ratio" == "wide" ]
			then
			echo 480x192
			exit 0
			fi
	else
##Use the video's original resolution if it's iPod-kosher.
	#	if [ $origpx -le 230400 ]
	#		then
	#		echo $origres
	#		exit 0
	#		fi
		if [ "$ratio" == "4by3" ]
			then
			echo 480x360
			exit 0
			fi
		if [ "$ratio" == "16by9" ]
			then
			echo 640x360
			exit 0
			fi
		if [ "$ratio" == "wide" ]
			then
			echo 640x272
			exit 0
			fi
		fi
echo 480x360
exit 0
fi

## If really weird stuff happens, fallback to regular res.
echo 320x240

exit 0
